apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/argocd/overlays/homelab
  - ../../infra/metallb/overlays/homelab
  - ../../infra/traefik/overlays/homelab
  - ../../infra/monitoring/overlays/homelab
  - ../../apps/overlays/homelab
