apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ipaddresspool.yaml
  - l2advertisement.yaml
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.8
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
